import type { ContentTypeDef } from '../types/admin.types';

/**
 * Every collection the admin can reach, in one place.
 *
 * Collection names come from firestore.rules. Field lists are the shapes the
 * rules imply (authorId, userId, buyerId, sellerId, posterId, createdBy,
 * followerId) plus the fields each feature needs — adjust a field here and the
 * list view, the editor and the search all follow. Nothing else needs touching.
 */
export const CONTENT_TYPES: ContentTypeDef[] = [
  /* ---------------------------------------------------------------- */
  /* Creative work                                                     */
  /* ---------------------------------------------------------------- */
  {
    id: 'works',
    collection: 'Works',
    label: 'Work',
    plural: 'Works',
    group: 'content',
    icon: 'bookOutline',
    titleField: 'title',
    ownerField: 'authorId',
    createdField: 'createdAt',
    statusField: 'status',
    searchFields: ['title'],
    description: 'Long-form pieces. Chapters hang off these.',
    fields: [
      { key: 'title', label: 'Title', kind: 'string', column: true, editable: true, width: 'w-64' },
      { key: 'authorId', label: 'Author', kind: 'reference', refCollection: 'Users', column: true },
      { key: 'genre', label: 'Genre', kind: 'string', column: true, editable: true },
      { key: 'status', label: 'Status', kind: 'enum', column: true, editable: true,
        options: ['draft', 'published', 'hidden', 'removed'] },
      { key: 'coverUrl', label: 'Cover', kind: 'image', editable: true },
      { key: 'synopsis', label: 'Synopsis', kind: 'text', editable: true },
      { key: 'tags', label: 'Tags', kind: 'array', editable: true },
      { key: 'chapterCount', label: 'Chapters', kind: 'number', column: true },
      { key: 'readCount', label: 'Reads', kind: 'number', column: true },
      { key: 'featured', label: 'Featured', kind: 'boolean', column: true, editable: true },
      { key: 'createdAt', label: 'Created', kind: 'timestamp', column: true },
      { key: 'updatedAt', label: 'Updated', kind: 'timestamp' },
    ],
    rowActions: [
      { id: 'feature', label: 'Feature on home', patch: { featured: true }, permission: 'content.write',
        when: (r) => !r.featured },
      { id: 'unfeature', label: 'Remove from home', patch: { featured: false }, permission: 'content.write',
        when: (r) => !!r.featured },
      { id: 'hide', label: 'Hide from readers', patch: { status: 'hidden' }, tone: 'warning',
        permission: 'content.write', when: (r) => r.status !== 'hidden',
        confirm: 'Hide this work? It stays in the author’s library but disappears from public views.' },
      { id: 'restore', label: 'Restore', patch: { status: 'published' }, permission: 'content.write',
        when: (r) => r.status === 'hidden' || r.status === 'removed' },
    ],
  },
  {
    id: 'chapters',
    collection: 'Chapters',
    label: 'Chapter',
    plural: 'Chapters',
    group: 'content',
    icon: 'documentTextOutline',
    titleField: 'title',
    ownerField: 'authorId',
    createdField: 'createdAt',
    statusField: 'status',
    searchFields: ['title'],
    fields: [
      { key: 'title', label: 'Title', kind: 'string', column: true, editable: true, width: 'w-64' },
      { key: 'workId', label: 'Work', kind: 'reference', refCollection: 'Works', column: true },
      { key: 'authorId', label: 'Author', kind: 'reference', refCollection: 'Users', column: true },
      { key: 'order', label: 'No.', kind: 'number', column: true, editable: true, width: 'w-16' },
      { key: 'status', label: 'Status', kind: 'enum', column: true, editable: true,
        options: ['draft', 'published', 'hidden'] },
      { key: 'wordCount', label: 'Words', kind: 'number', column: true },
      { key: 'content', label: 'Body', kind: 'richtext', editable: true },
      { key: 'createdAt', label: 'Created', kind: 'timestamp', column: true },
    ],
    rowActions: [
      { id: 'hide', label: 'Hide chapter', patch: { status: 'hidden' }, tone: 'warning',
        permission: 'content.write', when: (r) => r.status !== 'hidden' },
      { id: 'restore', label: 'Restore', patch: { status: 'published' }, permission: 'content.write',
        when: (r) => r.status === 'hidden' },
    ],
  },
  {
    id: 'prompts',
    collection: 'Prompts',
    label: 'Prompt',
    plural: 'Prompts',
    group: 'content',
    icon: 'bulbOutline',
    titleField: 'text',
    ownerField: 'userId',
    createdField: 'createdAt',
    searchFields: ['text'],
    description: 'Writing prompts. Set `curated` to surface one in the daily slot.',
    fields: [
      { key: 'text', label: 'Prompt', kind: 'text', column: true, editable: true, width: 'w-96' },
      { key: 'userId', label: 'Author', kind: 'reference', refCollection: 'Users', column: true },
      { key: 'category', label: 'Category', kind: 'string', column: true, editable: true },
      { key: 'curated', label: 'Curated', kind: 'boolean', column: true, editable: true },
      { key: 'usageCount', label: 'Used', kind: 'number', column: true },
      { key: 'createdAt', label: 'Created', kind: 'timestamp', column: true },
    ],
    rowActions: [
      { id: 'curate', label: 'Add to curated set', patch: { curated: true }, permission: 'content.write',
        when: (r) => !r.curated },
      { id: 'uncurate', label: 'Remove from curated set', patch: { curated: false },
        permission: 'content.write', when: (r) => !!r.curated },
    ],
  },

  /* ---------------------------------------------------------------- */
  /* Community                                                         */
  /* ---------------------------------------------------------------- */
  {
    id: 'posts',
    collection: 'Posts',
    label: 'Post',
    plural: 'Posts',
    group: 'community',
    icon: 'chatbubblesOutline',
    titleField: 'body',
    ownerField: 'authorId',
    createdField: 'createdAt',
    statusField: 'status',
    fields: [
      { key: 'body', label: 'Post', kind: 'text', column: true, editable: true, width: 'w-96' },
      { key: 'authorId', label: 'Author', kind: 'reference', refCollection: 'Users', column: true },
      { key: 'groupId', label: 'Group', kind: 'reference', refCollection: 'Groups', column: true },
      { key: 'status', label: 'Status', kind: 'enum', column: true, editable: true,
        options: ['visible', 'flagged', 'hidden'] },
      { key: 'reportCount', label: 'Reports', kind: 'number', column: true, width: 'w-20' },
      { key: 'likeCount', label: 'Likes', kind: 'number', column: true, width: 'w-20' },
      { key: 'imageUrl', label: 'Image', kind: 'image' },
      { key: 'createdAt', label: 'Posted', kind: 'timestamp', column: true },
    ],
    rowActions: [
      { id: 'hide', label: 'Take down', patch: { status: 'hidden' }, tone: 'danger',
        permission: 'content.write', when: (r) => r.status !== 'hidden',
        confirm: 'Take this post down? The author is notified.' },
      { id: 'clear', label: 'Clear flags', patch: { status: 'visible', reportCount: 0 },
        permission: 'content.write', when: (r) => r.status === 'flagged' || (r.reportCount ?? 0) > 0 },
    ],
  },
  {
    id: 'comments',
    collection: 'Comments',
    label: 'Comment',
    plural: 'Comments',
    group: 'community',
    icon: 'chatbubbleEllipsesOutline',
    titleField: 'body',
    ownerField: 'authorId',
    createdField: 'createdAt',
    statusField: 'status',
    fields: [
      { key: 'body', label: 'Comment', kind: 'text', column: true, editable: true, width: 'w-96' },
      { key: 'authorId', label: 'Author', kind: 'reference', refCollection: 'Users', column: true },
      { key: 'parentType', label: 'On', kind: 'string', column: true },
      { key: 'parentId', label: 'Target', kind: 'string', column: true },
      { key: 'status', label: 'Status', kind: 'enum', column: true, editable: true,
        options: ['visible', 'flagged', 'hidden'] },
      { key: 'reportCount', label: 'Reports', kind: 'number', column: true, width: 'w-20' },
      { key: 'createdAt', label: 'Posted', kind: 'timestamp', column: true },
    ],
    rowActions: [
      { id: 'hide', label: 'Take down', patch: { status: 'hidden' }, tone: 'danger',
        permission: 'content.write', when: (r) => r.status !== 'hidden' },
      { id: 'clear', label: 'Clear flags', patch: { status: 'visible', reportCount: 0 },
        permission: 'content.write', when: (r) => (r.reportCount ?? 0) > 0 },
    ],
  },
  {
    id: 'groups',
    collection: 'Groups',
    label: 'Group',
    plural: 'Groups',
    group: 'community',
    icon: 'peopleCircleOutline',
    titleField: 'name',
    ownerField: 'createdBy',
    createdField: 'createdAt',
    searchFields: ['name'],
    fields: [
      { key: 'name', label: 'Name', kind: 'string', column: true, editable: true, width: 'w-56' },
      { key: 'createdBy', label: 'Owner', kind: 'reference', refCollection: 'Users', column: true },
      { key: 'visibility', label: 'Visibility', kind: 'enum', column: true, editable: true,
        options: ['public', 'private', 'invite'] },
      { key: 'memberCount', label: 'Members', kind: 'number', column: true },
      { key: 'description', label: 'Description', kind: 'text', editable: true },
      { key: 'createdAt', label: 'Created', kind: 'timestamp', column: true },
    ],
  },
  {
    id: 'group-members',
    collection: 'GroupMembers',
    label: 'Membership',
    plural: 'Group members',
    group: 'community',
    icon: 'personAddOutline',
    titleField: 'userId',
    ownerField: 'userId',
    createdField: 'joinedAt',
    hidden: true,
    fields: [
      { key: 'groupId', label: 'Group', kind: 'reference', refCollection: 'Groups', column: true },
      { key: 'userId', label: 'Member', kind: 'reference', refCollection: 'Users', column: true },
      { key: 'role', label: 'Role', kind: 'enum', column: true, editable: true,
        options: ['member', 'moderator', 'owner'] },
      { key: 'joinedAt', label: 'Joined', kind: 'timestamp', column: true },
    ],
  },
  {
    id: 'follows',
    collection: 'Follows',
    label: 'Follow',
    plural: 'Follows',
    group: 'community',
    icon: 'gitNetworkOutline',
    titleField: 'followerId',
    ownerField: 'followerId',
    createdField: 'createdAt',
    hidden: true,
    fields: [
      { key: 'followerId', label: 'Follower', kind: 'reference', refCollection: 'Users', column: true },
      { key: 'followingId', label: 'Follows', kind: 'reference', refCollection: 'Users', column: true },
      { key: 'createdAt', label: 'Since', kind: 'timestamp', column: true },
    ],
  },

  /* ---------------------------------------------------------------- */
  /* Market                                                            */
  /* ---------------------------------------------------------------- */
  {
    id: 'listings',
    collection: 'GhostwriterListings',
    label: 'Listing',
    plural: 'Ghostwriter listings',
    group: 'market',
    icon: 'pricetagsOutline',
    titleField: 'title',
    ownerField: 'userId',
    createdField: 'createdAt',
    statusField: 'status',
    searchFields: ['title'],
    fields: [
      { key: 'title', label: 'Listing', kind: 'string', column: true, editable: true, width: 'w-64' },
      { key: 'userId', label: 'Seller', kind: 'reference', refCollection: 'Users', column: true },
      { key: 'rate', label: 'Rate', kind: 'money', column: true, editable: true },
      { key: 'currency', label: 'Currency', kind: 'string', editable: true },
      { key: 'turnaroundDays', label: 'Turnaround', kind: 'number', column: true, editable: true },
      { key: 'status', label: 'Status', kind: 'enum', column: true, editable: true,
        options: ['pending', 'active', 'paused', 'rejected'] },
      { key: 'description', label: 'Description', kind: 'text', editable: true },
      { key: 'createdAt', label: 'Listed', kind: 'timestamp', column: true },
    ],
    rowActions: [
      { id: 'approve', label: 'Approve listing', patch: { status: 'active' }, permission: 'market.write',
        when: (r) => r.status === 'pending' },
      { id: 'reject', label: 'Reject listing', patch: { status: 'rejected' }, tone: 'danger',
        permission: 'market.write', when: (r) => r.status === 'pending',
        confirm: 'Reject this listing? The seller sees the rejection in their dashboard.' },
      { id: 'pause', label: 'Pause', patch: { status: 'paused' }, tone: 'warning',
        permission: 'market.write', when: (r) => r.status === 'active' },
    ],
  },
  {
    id: 'orders',
    collection: 'Orders',
    label: 'Order',
    plural: 'Orders',
    group: 'market',
    icon: 'receiptOutline',
    titleField: 'id',
    ownerField: 'buyerId',
    createdField: 'createdAt',
    statusField: 'status',
    fields: [
      { key: 'listingId', label: 'Listing', kind: 'reference', refCollection: 'GhostwriterListings', column: true },
      { key: 'buyerId', label: 'Buyer', kind: 'reference', refCollection: 'Users', column: true },
      { key: 'sellerId', label: 'Seller', kind: 'reference', refCollection: 'Users', column: true },
      { key: 'amount', label: 'Amount', kind: 'money', column: true },
      { key: 'currency', label: 'Currency', kind: 'string', column: true, width: 'w-20' },
      { key: 'status', label: 'Status', kind: 'enum', column: true, editable: true,
        options: ['pending', 'in_progress', 'delivered', 'completed', 'disputed', 'cancelled', 'refunded'] },
      { key: 'dueAt', label: 'Due', kind: 'timestamp', column: true },
      { key: 'createdAt', label: 'Placed', kind: 'timestamp', column: true },
      { key: 'notes', label: 'Notes', kind: 'text', editable: true },
    ],
    rowActions: [
      { id: 'resolve', label: 'Mark resolved', patch: { status: 'completed' }, permission: 'market.write',
        when: (r) => r.status === 'disputed' },
      { id: 'cancel', label: 'Cancel order', patch: { status: 'cancelled' }, tone: 'danger',
        permission: 'market.write', confirm: 'Cancel this order? Payment capture stops immediately.',
        when: (r) => ['pending', 'in_progress'].includes(r.status) },
    ],
  },
  {
    id: 'payments',
    collection: 'Payments',
    label: 'Payment',
    plural: 'Payments',
    group: 'market',
    icon: 'cardOutline',
    titleField: 'reference',
    ownerField: 'userId',
    createdField: 'createdAt',
    statusField: 'status',
    searchFields: ['reference'],
    description: 'Read-only ledger. Refunds are issued by the backend, never written here directly.',
    fields: [
      { key: 'reference', label: 'Reference', kind: 'string', column: true, width: 'w-48' },
      { key: 'userId', label: 'User', kind: 'reference', refCollection: 'Users', column: true },
      { key: 'orderId', label: 'Order', kind: 'reference', refCollection: 'Orders', column: true },
      { key: 'amount', label: 'Amount', kind: 'money', column: true },
      { key: 'currency', label: 'Currency', kind: 'string', column: true, width: 'w-20' },
      { key: 'provider', label: 'Provider', kind: 'string', column: true },
      { key: 'status', label: 'Status', kind: 'enum', column: true,
        options: ['initiated', 'success', 'failed', 'refunded'] },
      { key: 'createdAt', label: 'Date', kind: 'timestamp', column: true },
    ],
  },
  {
    id: 'jobs',
    collection: 'Jobs',
    label: 'Job',
    plural: 'Jobs',
    group: 'market',
    icon: 'briefcaseOutline',
    titleField: 'title',
    ownerField: 'posterId',
    createdField: 'createdAt',
    statusField: 'status',
    searchFields: ['title'],
    fields: [
      { key: 'title', label: 'Job', kind: 'string', column: true, editable: true, width: 'w-64' },
      { key: 'posterId', label: 'Posted by', kind: 'reference', refCollection: 'Users', column: true },
      { key: 'budget', label: 'Budget', kind: 'money', column: true, editable: true },
      { key: 'currency', label: 'Currency', kind: 'string', editable: true },
      { key: 'status', label: 'Status', kind: 'enum', column: true, editable: true,
        options: ['open', 'in_review', 'filled', 'closed', 'flagged'] },
      { key: 'applicantCount', label: 'Applicants', kind: 'number', column: true },
      { key: 'description', label: 'Description', kind: 'text', editable: true },
      { key: 'createdAt', label: 'Posted', kind: 'timestamp', column: true },
    ],
    rowActions: [
      { id: 'close', label: 'Close job', patch: { status: 'closed' }, tone: 'warning',
        permission: 'market.write', when: (r) => r.status === 'open' },
      { id: 'reopen', label: 'Reopen', patch: { status: 'open' }, permission: 'market.write',
        when: (r) => r.status === 'closed' },
    ],
  },

  /* ---------------------------------------------------------------- */
  /* System                                                            */
  /* ---------------------------------------------------------------- */
  {
    id: 'notifications',
    collection: 'Notifications',
    label: 'Notification',
    plural: 'Notifications',
    group: 'system',
    icon: 'notificationsOutline',
    titleField: 'title',
    ownerField: 'userId',
    createdField: 'createdAt',
    fields: [
      { key: 'title', label: 'Title', kind: 'string', column: true, width: 'w-56' },
      { key: 'userId', label: 'Recipient', kind: 'reference', refCollection: 'Users', column: true },
      { key: 'type', label: 'Type', kind: 'string', column: true },
      { key: 'read', label: 'Read', kind: 'boolean', column: true },
      { key: 'body', label: 'Body', kind: 'text' },
      { key: 'createdAt', label: 'Sent', kind: 'timestamp', column: true },
    ],
  },
  {
    id: 'reminders',
    collection: 'Reminders',
    label: 'Reminder',
    plural: 'Reminders',
    group: 'system',
    icon: 'alarmOutline',
    titleField: 'label',
    ownerField: 'userId',
    createdField: 'createdAt',
    hidden: true,
    fields: [
      { key: 'label', label: 'Label', kind: 'string', column: true },
      { key: 'userId', label: 'User', kind: 'reference', refCollection: 'Users', column: true },
      { key: 'time', label: 'Time', kind: 'string', column: true },
      { key: 'enabled', label: 'On', kind: 'boolean', column: true },
      { key: 'createdAt', label: 'Created', kind: 'timestamp', column: true },
    ],
  },
  {
    id: 'streaks',
    collection: 'Streaks',
    label: 'Streak',
    plural: 'Streaks',
    group: 'system',
    icon: 'flameOutline',
    titleField: 'id',
    createdField: 'updatedAt',
    hidden: true,
    fields: [
      { key: 'id', label: 'User', kind: 'reference', refCollection: 'Users', column: true },
      { key: 'current', label: 'Current', kind: 'number', column: true },
      { key: 'longest', label: 'Longest', kind: 'number', column: true },
      { key: 'lastWriteAt', label: 'Last write', kind: 'timestamp', column: true },
    ],
  },
  {
    id: 'audit',
    collection: 'AdminAudit',
    label: 'Audit entry',
    plural: 'Audit log',
    group: 'system',
    icon: 'shieldCheckmarkOutline',
    titleField: 'action',
    createdField: 'at',
    description: 'Every write made through this panel, oldest at the bottom.',
    fields: [
      { key: 'at', label: 'When', kind: 'timestamp', column: true },
      { key: 'actorEmail', label: 'Admin', kind: 'string', column: true, width: 'w-56' },
      { key: 'action', label: 'Action', kind: 'string', column: true },
      { key: 'collection', label: 'Collection', kind: 'string', column: true },
      { key: 'documentId', label: 'Document', kind: 'string', column: true },
      { key: 'before', label: 'Before', kind: 'json' },
      { key: 'after', label: 'After', kind: 'json' },
    ],
  },
];

export const contentTypeById = (id: string): ContentTypeDef | undefined =>
  CONTENT_TYPES.find((t) => t.id === id);

export const contentTypeByCollection = (name: string): ContentTypeDef | undefined =>
  CONTENT_TYPES.find((t) => t.collection === name);

export const GROUP_LABELS: Record<string, string> = {
  content: 'Writing',
  community: 'Community',
  market: 'Market',
  system: 'System',
};
